version: "3.1"

services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env.db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env.db
    ports:
      - "5050:80"
    depends_on:
      - database

networks:
  pong-network:
    driver: bridge
